//Generated by https://www.skeleton.dev/docs/generator
import type { CustomThemeConfig } from '@skeletonlabs/tw-plugin';

export const dddSkeletonTheme: CustomThemeConfig = {
	name: 'ddd-skeleton-theme',
	properties: {
		// =~= Theme Properties =~=
		'--theme-font-family-base': `system-ui`,
		'--theme-font-family-heading': `system-ui`,
		'--theme-font-color-base': '0 0 0',
		'--theme-font-color-dark': '255 255 255',
		'--theme-rounded-base': '12px',
		'--theme-rounded-container': '8px',
		'--theme-border-base': '0px',
		// =~= Theme On-X Colors =~=
		'--on-primary': '0 0 0',
		'--on-secondary': '0 0 0',
		'--on-tertiary': '0 0 0',
		'--on-success': '0 0 0',
		'--on-warning': '0 0 0',
		'--on-error': '255 255 255',
		'--on-surface': '0 0 0',
		// =~= Theme Colors  =~=
		// primary | #ff9930
		'--color-primary-50': '255 240 224', // #fff0e0
		'--color-primary-100': '255 235 214', // #ffebd6
		'--color-primary-200': '255 230 203', // #ffe6cb
		'--color-primary-300': '255 214 172', // #ffd6ac
		'--color-primary-400': '255 184 110', // #ffb86e
		'--color-primary-500': '255 153 48', // #ff9930
		'--color-primary-600': '230 138 43', // #e68a2b
		'--color-primary-700': '191 115 36', // #bf7324
		'--color-primary-800': '153 92 29', // #995c1d
		'--color-primary-900': '125 75 24', // #7d4b18
		// secondary | #ffffff
		'--color-secondary-50': '255 255 255', // #ffffff
		'--color-secondary-100': '255 255 255', // #ffffff
		'--color-secondary-200': '255 255 255', // #ffffff
		'--color-secondary-300': '255 255 255', // #ffffff
		'--color-secondary-400': '255 255 255', // #ffffff
		'--color-secondary-500': '255 255 255', // #ffffff
		'--color-secondary-600': '230 230 230', // #e6e6e6
		'--color-secondary-700': '191 191 191', // #bfbfbf
		'--color-secondary-800': '153 153 153', // #999999
		'--color-secondary-900': '125 125 125', // #7d7d7d
		// tertiary | #96c6ca
		'--color-tertiary-50': '239 246 247', // #eff6f7
		'--color-tertiary-100': '234 244 244', // #eaf4f4
		'--color-tertiary-200': '229 241 242', // #e5f1f2
		'--color-tertiary-300': '213 232 234', // #d5e8ea
		'--color-tertiary-400': '182 215 218', // #b6d7da
		'--color-tertiary-500': '150 198 202', // #96c6ca
		'--color-tertiary-600': '135 178 182', // #87b2b6
		'--color-tertiary-700': '113 149 152', // #719598
		'--color-tertiary-800': '90 119 121', // #5a7779
		'--color-tertiary-900': '74 97 99', // #4a6163
		// success | #84cc16
		'--color-success-50': '237 247 220', // #edf7dc
		'--color-success-100': '230 245 208', // #e6f5d0
		'--color-success-200': '224 242 197', // #e0f2c5
		'--color-success-300': '206 235 162', // #ceeba2
		'--color-success-400': '169 219 92', // #a9db5c
		'--color-success-500': '132 204 22', // #84cc16
		'--color-success-600': '119 184 20', // #77b814
		'--color-success-700': '99 153 17', // #639911
		'--color-success-800': '79 122 13', // #4f7a0d
		'--color-success-900': '65 100 11', // #41640b
		// warning | #ffc13a
		'--color-warning-50': '255 246 225', // #fff6e1
		'--color-warning-100': '255 243 216', // #fff3d8
		'--color-warning-200': '255 240 206', // #fff0ce
		'--color-warning-300': '255 230 176', // #ffe6b0
		'--color-warning-400': '255 212 117', // #ffd475
		'--color-warning-500': '255 193 58', // #ffc13a
		'--color-warning-600': '230 174 52', // #e6ae34
		'--color-warning-700': '191 145 44', // #bf912c
		'--color-warning-800': '153 116 35', // #997423
		'--color-warning-900': '125 95 28', // #7d5f1c
		// error | #a80032
		'--color-error-50': '242 217 224', // #f2d9e0
		'--color-error-100': '238 204 214', // #eeccd6
		'--color-error-200': '233 191 204', // #e9bfcc
		'--color-error-300': '220 153 173', // #dc99ad
		'--color-error-400': '194 77 112', // #c24d70
		'--color-error-500': '168 0 50', // #a80032
		'--color-error-600': '151 0 45', // #97002d
		'--color-error-700': '126 0 38', // #7e0026
		'--color-error-800': '101 0 30', // #65001e
		'--color-error-900': '82 0 25', // #520019
		// surface | #eaeaea
		'--color-surface-50': '252 252 252', // #fcfcfc
		'--color-surface-100': '251 251 251', // #fbfbfb
		'--color-surface-200': '250 250 250', // #fafafa
		'--color-surface-300': '247 247 247', // #f7f7f7
		'--color-surface-400': '240 240 240', // #f0f0f0
		'--color-surface-500': '234 234 234', // #eaeaea
		'--color-surface-600': '211 211 211', // #d3d3d3
		'--color-surface-700': '176 176 176', // #b0b0b0
		'--color-surface-800': '140 140 140', // #8c8c8c
		'--color-surface-900': '115 115 115' // #737373
	}
};
